sudo: false

language: node_js

node_js:
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - npm i nyc codecov --global

script:
  - npm run test

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
